server:
  port: 8082

spring:
  jackson:
    serialization:
      indent_output: true
  config:
    name: spring-boot-liquibase
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    change-log: classpath:/db/master.xml